const VALID_EMAIL_TYPE = 'VALID_EMAIL_TYPE';
const VALID_WHITE_SPACE = 'VALID_WHITE_SPACE';
const VALID_FIELD_LENGTH = 'VALID_FIELD_LENGTH';
const VALID_PASSWORD = 'VALID_PASSWORD';

export const typeOfValidation = {
  VALID_EMAIL_TYPE,
  VALID_WHITE_SPACE,
  VALID_FIELD_LENGTH,
  VALID_PASSWORD,
};
